#!/usr/bin/python3
print("/*this file is automatically generated by gen_isr_wrapper.py*/")
print(".code64")
print(".section .text")
for i in range(0, 256):
    print(".globl _isr" + str(i))
print(".align 16")
print()
print()
print()


have_error = [8, 10, 11, 12, 13, 14] #intel 6.15 interrupt with exseption error code

for i in range(0, 256):
    print("_isr" + str(i) + ":")
    if i not in have_error:
        print("    push $0")
    print("    push $" + str(i))
    print("    jmp isr_wrapper")
    print()

#http://www.x86-64.org/documentation/abi.pdf
#page 21, not save register

reg = ["rax", "rcx", "rdx", "rsi", "rdi" ,"r8", "r9", "r10", "r11"]

#interrupt controler
print("isr_wrapper:")
for cur_reg in reg[::-1]:
    print("    push %" + cur_reg) #push registers on stack

print()
print("    call interrupt_handler")
print()

for cur_reg in reg:
    print("    pop %" + cur_reg) #pop registers on stack

print()
print("    add $16, %rsp") #pop from stack error_code and id_interrupt
print("    iretq")
